import Head from "next/head";
import Header from "../components/Header";
import Card from "../components/Card";
import Footer from "../components/Footer";
import AdSide from "../components/AdSide";
import Frameworks from "../components/Frameworks";
import ProjectIdeas from "../components/ProjectIdeas";
import ReactCard from "../components/ReactCard";
import ThankyouCard from "../components/ThankyouCard";

const frameworksData = [
  {
    image:
      "https://th.bing.com/th/id/R.b8538125cbb29114a62062d82b2c861e?rik=vo60SDgTw8oQMw&pid=ImgRaw&r=0",
    name: "React",
    isTrue: true,
  },
  {
    image: "https://dkny.oss-cn-hangzhou.aliyuncs.com/1/icons/vue.svg",
    name: "vue Js",
    isTrue: true,
  },
  {
    image: "https://dkny.oss-cn-hangzhou.aliyuncs.com/1/icons/angular.svg",
    name: "Angular",
    isTrue: false,
  },
  {
    image: "https://dkny.oss-cn-hangzhou.aliyuncs.com/1/icons/svelte.svg",
    name: "svelte",
    isTrue: false,
  },
];

type Props = {
  searchResults: any;
};

const Home = ({ searchResults }: Props) => {
  return (
    <div>
      <Head>
        <title>F u n J a v a S c r i p t</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Unofficial_JavaScript_logo_2.svg/2048px-Unofficial_JavaScript_logo_2.svg.png"
        />
      </Head>
      <Header />
      <Card />
      <AdSide />
      <ProjectIdeas />
      <section className="flex justify-center bg-[#015871] pb-10">
        {frameworksData.map((data, Index) => (
          <div key={Index}>
            <Frameworks
              image={data.image}
              name={data.name}
              isTrue={data.isTrue}
            />
          </div>
        ))}
      </section>
      <ReactCard searchResults={searchResults} />
      <ThankyouCard />
      <Footer />
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  const searchResults = await fetch(
    "https://sashenportfolio.herokuapp.com/retrieve/conversation"
  ).then((res) => res.json());

  return {
    props: {
      searchResults,
    },
  };
}
